name: duxbe_kds
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  animations: ^2.0.11
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^17.0.1
  hancod_theme:
    path: packages/hancod_theme
  http: ^1.2.2
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  native_device_orientation: ^2.0.3
  path: ^1.9.0
  phone_form_field: ^10.0.8
  pinput:
    path: packages/Flutter_Pinput
  reactive_forms: ^18.2.2
  reactive_forms_annotations: ^8.0.1
  riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  riverpod_sqflite: ^0.3.3
  scaled_app: ^2.3.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sqflite_common_ffi_web: ^1.0.1+1
  supabase_flutter: ^2.12.0
  timezone: ^0.11.0
  toastification: ^3.0.3
  upgrader: ^12.5.0

dependency_overrides:
  flutter_keyboard_visibility_web:
    path: packages/flutter_keyboard_visibility_web-2.0.0
  intl: ^0.20.2
  form_builder_extra_fields: ^12.0.0
  flutter_form_builder: ^10.0.1
  dropdown_search: ^6.0.2
  analyzer_plugin: 0.13.10

dev_dependencies:
  build_runner: 2.13.1
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  msix: ^3.16.13
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
    - assets/markdowns/
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: NatoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Light.ttf
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/shared/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

msix_config:
  display_name: Duxbe
  publisher_display_name: Hancod Digital Pvt Lmt.
  identity_name: com.duxbe.kds
  msix_version: 1.0.0.0
  logo_path: .\assets\images\duxbe_whitebg.png
  capabilities: internetClient, location, microphone, webcam
  windows_build_args: -t lib\main_production.dart --no-tree-shake-icons --dart-define-from-file=env\env.prod.json
  sign_msix: true

 
